config/routes.rb
Rails.application.routes.draw do
  get 'authors/new'
  get 'authors/show'
  get 'authors/index'
  get 'sessions/new'
  get :signup,       to: 'admin_users#new'
  resources :admin_users
  resources :authors
  resources :books
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  private

    def downcase_email
      self.email = email.downcase
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
    validates :name, presence: true
    validates :email, presence: true
    validates :introduction, length: { maximum: 140 }
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author
    validates :title, presence: true
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :logged_in_admin_user, only: [:index, :new, :show, :edit, :update]
  before_action :correct_admin_user,   only: [:edit, :update]
  
  def index
    @admin_users = AdminUser.all
  end

  def new
    @admin_user = AdminUser.new
  end

  def show
    @admin_user = AdminUser.find(params[:id])
  end

  def create
    @admin_user = AdminUser.new(admin_user_params)
    if @admin_user.save
      flash[:success] = "登録が完了しました"
      redirect_to @admin_user
    else
      render 'new'
    end
  end

  def edit
    @admin_user = AdminUser.find(params[:id])
  end

  def update
    @admin_user = AdminUser.find(params[:id])
    if @admin_user.update_attributes(admin_user_params_update)
      flash[:success] = "プロフィールが更新されました！"
      redirect_to @admin_user
    else
      render 'edit'
    end
  end

  private

  # ユーザー新規作成時に許可する属性
  def admin_user_params
    params.require(:admin_user).permit(:name, :email, :password,
                                   :password_confirmation)
  end

  # プロフィール編集時に許可する属性
  def admin_user_params_update
    params.require(:admin_user_params).permit(:name, :email)
  end
  
  # 正しいユーザーかどうか確認
  def correct_admin_user
    @admin_user = AdminUser.find(params[:id])
    if !current_admin_user?(@admin_user)
      flash[:danger] = "このページへはアクセスできません"
      redirect_to(root_url)
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
    # ログイン済みユーザーかどうか確認
    def logged_in_admin_user
      unless logged_in?
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :logged_in_admin_user, only: [:index, :new, :show, :edit, :update]
  before_action :correct_admin_user,   only: [:edit, :update]

  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end
  
  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "登録が完了しました"
      redirect_to @author
    else
      render 'new'
    end
  end
  
  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(author_params_update)
      flash[:success] = "プロフィールが更新されました！"
      redirect_to @author
    else
      render 'edit'
    end
  end

  private

    def author_params
      params.require(:author).permit(:name, :email, :introduction)
    end
    
    def author_params_update
      params.require(:author_params).permit(:name, :email, :introduction, :sex)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_admin_user, only: [:index, :new, :show, :edit, :update]
  before_action :correct_admin_user,   only: [:edit, :update]

  def index
    @books = Book.all
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "登録が完了しました"
      redirect_to @book
    else
      render 'new'
    end
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params_update)
      flash[:success] = "プロフィールが更新されました！"
      redirect_to @book
    else
      render 'edit'
    end
  end
  
  private

    def book_params
      params.require(:book).permit(:title)
    end
    
    def book_params_update
      params.require(:book).permit(:title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = AdminUser.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to admin_user_url(current_admin_user.id)
    else
      flash.now[:danger] = 'メールアドレスとパスワードの組み合わせが誤っています'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to "/login"
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Authors-Manager"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(admin_user)
    session[:admin_user_id] = admin_user.id
  end

  def current_admin_user
    if session[:admin_user_id]
      @current_admin_user ||= AdminUser.find_by(id: session[:admin_user_id])
    end
  end

  def logged_in?
    !current_admin_user.nil?
  end

  def log_out
    session.delete(:admin_user_id)
    @current_admin_user = nils
  end
  
  # 渡されたユーザーがログイン済みユーザーであればtrueを返す
  def current_admin_user?(admin_user)
    admin_user == current_admin_user
  end
end

app/views/admin_users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@admin_user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    <div class = 'form-group'>
        <%= f.label '名前' %>
        <%= f.text_field :name, class: 'form-control', id: 'admin_user_name' %>
      </div>
    <div class = 'form-group'>
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control', id: 'admin_user_email' %>
    </div>
    <%= f.submit "更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin_users/index.html.erb
<% provide(:title, '管理ユーザー一覧') %>
<div class="container">
  <h1>管理ユーザー一覧</h1>
  <p><%= link_to '新規追加', new_admin_user_path, class: 'btn btn-primary' %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>名前</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @admin_users.each do |admin_user| %>
        <tr>
          <td><%= admin_user.id %></td>
          <td><%= admin_user.name %></td>
          <td><%= admin_user.email %></td>
          <td><%= link_to '詳細', admin_user %></td>
          <td><%= link_to '編集', edit_admin_user_path(admin_user) %></td>
          <td><%= link_to '削除', admin_user, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin_users/new.html.erb
<% provide(:title, 'ユーザー登録') %>
<h1>ユーザー登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @admin_user, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class = 'form-group'>
        <%= f.label '名前' %>
        <%= f.text_field :name, class: 'form-control', id: 'admin_user_name' %>
      </div>
      <div class = 'form-group'>
        <%= f.label 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control', id: 'admin_user_email' %>
      </div>
      <div class = 'form-group'>
        <%= f.label 'パスワード' %>
        <%= f.password_field :password, class: 'form-control', id: 'admin_user_password' %>
      </div>
      <div class = 'form-group'>
        <%= f.label 'パスワード(確認)' %>
        <%= f.password_field :password_confirmation, class: 'form-control', id: 'admin_user_password_confirmation' %>
      </div>
      <%= f.submit nil, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin_users/show.html.erb
<h1>プロフィール</h1>
<%= @admin_user.id %>,<%= @admin_user.name %>, <%= @admin_user.email %><br>
<%= @admin_user.created_at %>, <%= @admin_user.updated_at %><br>
<% if current_admin_user == @admin_user %>
    <div class="account-edit"><%= link_to "プロフィール編集", edit_admin_user_path(@admin_user) %></div>
<% end %>

app/views/authors/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@author) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class = 'form-group'>
        <%= f.label "名前" %>
        <%= f.text_field :name, class: 'form-control', id: 'author_name' %>
      </div>
      <div class = 'form-group'>
        <%= f.label "メールアドレス" %>
        <%= f.email_field :email, class: 'form-control', id: 'author_email' %>
      </div>
      <div class = 'form-group'>
        <%= f.label "説明" %>
        <%= f.text_field :introduction, class: 'form-control', id: 'author_introduction' %>
      </div>
      <div class = 'form-group'>
        <%= f.label "性別" %>
        <%= f.text_field :sex, class: 'form-control', id: 'author_sex' %>
      </div>
    <%= f.submit "更新する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/authors/index.html.erb
<% provide(:title, '著者一覧') %>
<div class="container">
  <h1>著者一覧</h1>
  <p><%= link_to '新規追加', new_author_path, class: 'btn btn-primary' %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>名前</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.id %></td>
          <td><%= author.name %></td>
          <td><%= author.email %></td>
          <td><%= link_to '詳細', author %></td>
          <td><%= link_to '編集', edit_author_path(author) %></td>
          <td><%= link_to '削除', author, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/index.html.erb
<% provide(:title, '書籍一覧') %>
<div class="container">
  <h1>書籍一覧</h1>
  <p><%= link_to '新規追加', new_book_path, class: 'btn btn-primary' %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>著者</th>
        <th>タイトル</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.id %></td>
          <td><%= author.name %></td>
          <td><%= book.title %></td>
          <td><%= link_to '詳細', author %></td>
          <td><%= link_to '編集', edit_author_path(author) %></td>
          <td><%= link_to '削除', author, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<% provide(:title, "書籍登録") %>
<h1>書籍登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @book, local: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    　<div class = 'form-group'>
        <%= f.label "著者" %>
        <%= f.collection_select(:author_id, Author.all, :id, :name, {}, {class:"select-box", id:"mentor-skill"}) %>
      </div>
      <div class = 'form-group'>
        <%= f.label "書籍タイトル" %>
        <%= f.text_field :title, class: 'form-control', id: 'book_title' %>
      </div>
      <div class = 'form-group'>
        <%= f.label "出版日" %>
        <%= f.date_field :datetime, class: 'form-control', id: 'book_datetime' %>
      </div>
      <%= f.submit nil, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2021 Muranaka All Rights Reserved.</small>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
 <div class="container">
   <nav>
     <ul class="nav navbar-nav navbar-right">
       <% if logged_in? %>
         <li><%= link_to '著者一覧', '/authors' %></li>
         <li><%= link_to '書籍一覧', '/books' %></li>
         <li><%= link_to '管理ユーザー一覧', '/admin_users' %></li>
         <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
       <% end %>
     </ul>
   </nav>
 </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div id="page">
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>